USE `jfinal-angular`;

DROP TABLE IF EXISTS z_user;
CREATE TABLE IF NOT EXISTS z_user (
`userId` INT(11) NOT NULL AUTO_INCREMENT,
`username` VARCHAR(50) NOT NULL ,
`password` VARCHAR(30) NOT NULL ,
`email` VARCHAR(30) NOT NULL ,
`birth` DATETIME NOT NULL ,
`icon` VARCHAR(255) NOT NULL ,
PRIMARY KEY (`userId`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS z_game;
CREATE TABLE IF NOT EXISTS z_game (
`gameId` INT(11) NOT NULL AUTO_INCREMENT,
`gameName` VARCHAR(50) NOT NULL ,
`description` VARCHAR(1000) NOT NULL ,
`createdDate` DATETIME NOT NULL ,
`icon` VARCHAR(255) NOT NULL ,
PRIMARY KEY (`gameId`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS z_gamerecord;
CREATE TABLE IF NOT EXISTS z_gamerecord (
`recordId` INT(11) NOT NULL AUTO_INCREMENT,
`gameId` INT NOT NULL ,
`score` INT NOT NULL ,
`userId` INT NOT NULL ,
`gainDate` DATETIME NOT NULL ,
PRIMARY KEY (`recordId`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS z_usergame;
CREATE TABLE IF NOT EXISTS z_usergame (
`userGameId` INT(11) NOT NULL AUTO_INCREMENT,
`userId` INT NOT NULL ,
`gameId` INT NOT NULL ,
`joinedDate` DATETIME NOT NULL ,
PRIMARY KEY (`userGameId`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS z_leaderboard;
CREATE TABLE IF NOT EXISTS z_leaderboard (
`baseId` BIGINT(20) NOT NULL AUTO_INCREMENT,
`gameId` INT NOT NULL ,
`userId` INT NOT NULL ,
`score` INT NOT NULL ,
`rank` INT NOT NULL ,
PRIMARY KEY (`baseId`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

